server:
  port: 9002
  netty:
    connection-timeout: 5s
  shutdown: graceful
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/auth/realms/Bookshop
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    pool:
      max-create-connection-time: 5s
      initial-size: 5
      max-size: 10
  profiles:
    active: local
