server:
  port: 9002
  netty:
    connection-timeout: 5s
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5433/bookshop_order
    pool:
      max-create-connection-time: 5s
      initial-size: 5
      max-size: 10