apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      terminationGracePeriodSeconds: 20
      containers:
      - name: order-service
        image: kuzmin35/order-service:0.0.1-SNAPSHOT
        lifecycle:
          preStop:
            exec:
              command: [ "sh", "-c", "sleep 5" ]
        ports:
        - containerPort: 9001
        env:
          - name: POSTGRESQL_USERNAME
            value: user
          - name: POSTGRESQL_PASSWORD
            value: password
          - name: POSTGRESQL_R2DBC_URL
            value: r2dbc:postgresql://bookshop-order-postgresql:5432/bookshop_order
          - name: POSTGRESQL_JDBC_URL
            value: jdbc:postgresql://bookshop-order-postgresql:5432/bookshop_order
          - name: POSTGRESQL_SCHEMA
            value: orders
          - name: CATALOG_SERVICE_URL
            value: http://book-catalog-service:9001
        resources:
          requests:
            memory: "756Mi"
            cpu: "0.5"
          limits:
            memory: "756Mi"